name: Terraform Refresh State

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform-refreshing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1


      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Select or Create Workspace
        run: |
          terraform workspace select production || terraform workspace new production

      - name: Force Unlock State
        run: terraform force-unlock -force 390b9760-f698-f6ae-ee4d-15bebeeaac34 || true

      - name: Refresh Terraform State
        run: terraform plan -refresh-only -lock=false
